--- drivers/net/wireless/Makefile
+++ drivers/net/wireless/Makefile
@@ -56,5 +56,4 @@
 
 obj-$(CONFIG_IWM)	+= iwmc3200wifi/
 
-obj-$(CONFIG_BCM4329)	+= bcm4329/
 obj-$(CONFIG_ATH6K_LEGACY)	+= ath6kl/
